apiVersion: v2
name: sensa-ingress
description: A Helm chart for Sensa ingress rules for nginx-ingress
icon: https://helm.symphonyfs.net/symphonyai_sensa_netreveal_logo.jpg
type: application
version: 0.2.0
appVersion: "0.1.1"
