apiVersion: v2
name: sensa-secrets
description: A Helm chart for creating Sensa Kubernetes secrets
icon: https://helm.symphonyfs.net/symphonyai_sensa_netreveal_logo.jpg
type: application
version: 0.2.5
appVersion: "0.2.4"
