apiVersion: v1
kind: Service
metadata:
  name: {{ include "hermes.fullname" . }}
  labels:
    {{- include "hermes.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - nodePort: {{ .Values.service.nodePort }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: hermes
  selector:
    {{- include "hermes.selectorLabels" . | nindent 4 }}