{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zeus.serviceAccountName" . }}
  labels:
    {{- include "zeus.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
secrets:
  - name: {{ include "zeus.serviceAccountName" . }}-token
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zeus.serviceAccountName" . }}-token
  annotations:
    kubernetes.io/service-account.name: {{ include "zeus.serviceAccountName" . }}
type: kubernetes.io/service-account-token
{{- end }}
