{{- if .Values.server.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "trino.fullname" . }}-worker
spec:
  maxReplicas: {{ .Values.server.autoscaling.maxReplicas }}
  minReplicas: {{ .Values.server.workers }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "trino.fullname" . }}-worker
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.server.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}