apiVersion: v2
name: sensa-hooks
description: A chart of hooks for installing and upgrading Sensa
icon: https://helm.symphonyfs.net/symphonyai_sensa_netreveal_logo.jpg
type: application
version: 0.1.9
appVersion: "1.1.0"
