apiVersion: v1
kind: Service
metadata:
  name: {{ include "styx.fullname" . }}
  labels:
    {{- include "styx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - nodePort: {{ .Values.service.nodePort }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: styx
  selector:
    {{- include "styx.selectorLabels" . | nindent 4 }}