{{- $root := . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication required'
    nginx.ingress.kubernetes.io/auth-secret: prometheus-ingress-creds
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: "nginx"
  tls:
  - hosts:
    - {{ .Values.global.SENSA_WEB_HOST }}
    secretName: {{ .Values.global.SSL_SECRETS }}
  rules:
  - host: {{ .Values.global.SENSA_WEB_HOST }}
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/prometheus(/|$)(.*)"
        backend:
          service:
            name: prometheus-prometheus
            port:
              number: 9090
