{{- $secretObjOld := (lookup "v1" "Secret" .Release.Namespace .Values.sensaSecrets) | default dict }}
{{- $secretDataOld := (get $secretObjOld "data") | default dict }}
{{- $userPasswordOld := (get $secretDataOld "SENSA_USER_PASSWORD" | b64dec) }}
{{- $dbPasswordOld := (get $secretDataOld "SENSA_DB_PASSWORD" | b64dec) }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.tempSecrets }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-100"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
stringData:
  config.yaml: |
  SENSA_USER_PASSWORD: "{{ $userPasswordOld }}"
  SENSA_DB_PASSWORD: "{{ $dbPasswordOld }}"
