apiVersion: batch/v1
kind: Job
metadata:
  name: post-upgrade-reindex-job
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
 template:
   metadata:
     annotations:
       app.kubernetes.io/name: "{{ .Chart.Name }}"
   spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: meilisearch-reindex-job
          image: "{{ .Values.hyperkubeRepository }}:{{ .Values.hyperkubeTag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command:
            - /bin/bash
            - /scripts/meilisearch-reindex.sh
          env:
            - name: SENSA_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sensa-global-secrets
                  key: SENSA_USER_PASSWORD
            - name: NAMESPACE
              value: {{ .Release.Namespace | quote }}
      restartPolicy: Never

