{{- $secretObjOld := (lookup "v1" "Secret" .Release.Namespace .Values.tempSecrets) | default dict }}
{{- $secretDataOld := (get $secretObjOld "data") | default dict }}
{{- $userPasswordOld := (get $secretDataOld "SENSA_USER_PASSWORD" | b64dec) }}
{{- if ne $userPasswordOld .Values.global.PASSWORD }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sensa-admin-role
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sensa-admin-sa
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sensa-admin-rolebinding
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
subjects:
- kind: ServiceAccount
  name: sensa-admin-sa
  apiGroup: ""
roleRef:
  kind: Role
  name: sensa-admin-role
  apiGroup: ""
---
apiVersion: batch/v1
kind: Job
metadata:
  name: restart-services-after-pw-change
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    metadata:
      name: restart-services-after-pw-change
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: sensa-admin-sa
      containers:
        - name: hyperkube
          image: "{{ .Values.hyperkubeRepository }}:{{ .Values.hyperkubeTag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: NAMESPACE
              value: {{ .Release.Namespace | quote }}
          command:
           - /bin/bash
           - -c
           - |
             kubectl -n $NAMESPACE rollout restart statefulset redis-master redis-replicas hive-metastore

      restartPolicy: OnFailure
{{- end }}