{{- $secretObjOld := (lookup "v1" "Secret" .Release.Namespace .Values.tempSecrets) | default dict }}
{{- $secretDataOld := (get $secretObjOld "data") | default dict }}
{{- $userPasswordOld := (get $secretDataOld "SENSA_USER_PASSWORD" | b64dec) }}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace .Values.sensaSecrets) | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
{{- $dbPassword := (get $secretData "SENSA_DB_PASSWORD" | b64dec) }}
{{- if ne $userPasswordOld .Values.global.PASSWORD }}
apiVersion: batch/v1
kind: Job
metadata:
  name: update-db-passwords
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    metadata:
      name: update-db-passwords
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: hyperkube
          image: "{{ .Values.hyperkubeRepository }}:{{ .Values.hyperkubeTag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            {{- if $userPasswordOld }}
            {{- $dbPassword := (get $secretDataOld "SENSA_DB_PASSWORD" | b64dec) }}
            {{- end }}
            - name: DB_PASSWORD
              value: "{{ $dbPassword }}"
            - name: SENSA_SERVICES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sensa-global-secrets
                  key: SENSA_SERVICES_PASSWORD
            - name: SENSA_ENCRYPTION_SECRET
              valueFrom:
                secretKeyRef:
                  name: sensa-global-secrets
                  key: SENSA_ENCRYPTION_SECRET
            - name: SENSA_API_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: sensa-global-secrets
                  key: SENSA_API_KEY_SECRET
          volumeMounts:
            - name: sensasecrets-volume
              mountPath: /sensasecrets-volume
          command:
          - /bin/bash
          - /scripts/update-postgres-passwords.sh
      volumes:
        - name: sensasecrets-volume
          secret:
            secretName: sensa-global-secrets
      restartPolicy: OnFailure

{{- end }}
